#server:
#  port: 8081
#spring:
#  application:
#    name: item-service
#  cloud:
#    nacos:
#      server-addr: 192.168.29.129:8848
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://${hm.db.host}:3306/hm-item?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=America/New_York
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ${hm.db.pw}
#mybatis-plus:
#  configuration:
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  global-config:
#    db-config:
#      update-strategy: not_null
#      id-type: auto
#logging:
#  level:
#    com.hmall: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"
#knife4j:
#  enable: true
#  openapi:
#    title: 商品服务接口文档
#    description: "信息"
#    email: zhanghuyi@itcast.cn
#    concat: 虎哥
#    url: https://www.itcast.cn
#    version: v1.0.0
#    group:
#      default:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.hmall.item.controller

server:
  port: 8081
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # 这段配置无法生效，因为sentinel的bug，需要在VM option中配置-Dcsp.sentinel.dashboard.server=localhost:8090
        port: 8719
        clientIp: localhost:8082
      http-method-specify: true
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
hm:
  swagger:
    title: 商品服务接口文档
    package: com.hmall.item.controller
  db:
    database: hm-item